### ISSUE TITLE
Reinforcement indicator numbers can be seen through other blocks

### ISSUE THREAD

**Issue by mturley** [trevor99z/Reinforcement#2]
If possible, it would be very nice to prevent the reinforcement indicator numbers (20) from being visible when the reinforced block is covered up by another block. I used reinforced obsidian covered by regular stone/furnaces to line my hidden storage area, but if an invader came in and just looked around while holding obsidian they could see where it is hidden.

**Comment by trevor99z** [comment]
Fixed in [latest release](https://github.com/trevor99z/Reinforcement/releases/tag/1.19.4)
