### ISSUE TITLE
New Idea

### ISSUE THREAD

**Issue by Silent-Alchemist** [trevor99z/Reinforcement#7]
### Hello! I was wondering if you're still willing to update the project.

My idea would be the following:

**+ Reinforcement mode (/rm [group])**
   o No more accidental reinforcing of blocks. You'll have to toggle the reinforcement mode ON to reinforce blocks into the desired group.

**+  Ability to add different items with different reinforcement values.**
   o This would allow for further 'tiers' of reinforcements instead of just a single universal one. So players could reinforce with iron ingots, diamonds, stone, etc.

**+ Add reinforcement groups (/rgroup)**
   o This would allow players with the proper permissions in the group to bypass the reinforcement values by using something like /rb. It is currently annoying having to mine the block 20 times (default), even in creative mode, just to get rid of a block.
   o This could also have other permissions like allowing players to reinforce blocks that are under their group.

**+ Option to repair reinforcements (/rrepair)**
   o Currently, you can't repair reinforcements, which means reinforcements can degrade without you being able to maintain them unless you mine out the block yourself. Adding a command like /rrepair would take resources (of the same tier material) to restore the reinforcement back to 100% reinforcement tier health.

**+ Option to have tools only lose durability after the FINAL mine.**
   o It's not helpful that tools lose durability just trying to mine the reinforced block. With this config option, you could set it that once the reinforced block is completely mined,  it will then lose 1 durability (or configurable maybe).

**+ Add indicators when a certain mode is on or not.**
   o Currently, '/ri' has one indicator when reinforcement info mode is turned on, but has no indicators when you successfully turn it off. Although not very significant, it would definitely be user-friendly if this was added.
   o It would run similarly to this /ri [ON/OFF] or /rrepair [ON/OFF]. The ON/OFF argument would be an optional argument but can be used by players to ensure certain modes are on or off.
   o Indicators could be a simple as clearly stating in chat whether the mode is on or off: "Reinforcement Info mode turned (red)OFF."
   
   
That's all the ideas I have for now. If you have any questions/comments/concerns regarding this suggestion post, please let me know here or contact me via Discord: **Silent#8713**

**Comment by trevor99z** [comment]
These are great ideas. If I get some time, I will look into updating this plugin and adding these features! Thanks for the suggestions!

**Comment by Silent-Alchemist** [comment]
No problem! Your plugin is amazing btw!
I hope all goes well for you, life of an open-source developer isn't easy 🙏

(2 days later and I barely saw your reply, I'm sorry 😭)

**Comment by ReLyonel** [comment]
Good afternoon, I was testing this plugin in Paper 1.19.4 and it is excellent, since its code is very simple and does not affect almost anything to the server, this plugin is really great.

As the ideas of the publication support the idea of repairing the blocks either with emerald (so this resource is given more dependence) that each emerald repairs 1 level, but can not pass the set maximum of the reinforcement block (Reinforcement).

**Comment by trevor99z** [comment]
This issue will be addressed in the next version, I will be releasing it soon.

**Comment by trevor99z** [comment]
See [latest release](https://github.com/trevor99z/Reinforcement/releases/tag/1.19.4)
