### ISSUE TITLE
Error Paper 1.19.4

### ISSUE THREAD

**Issue by ReLyonel** [trevor99z/Reinforcement#8]
When I run the plugin I get the following error and when I check inside the reinforcement server it is disabled. Is there any incompatibility with paper 1.19.4 being a code almost new but more complete? since the 1.0 worked great for me on this same server: here I show the error, my version paper is 1.19.4 Build 538:
20.05 16:29:56 [Server] INFO [Reinforcement] Enabling Reinforcement v1.1
20.05 16:29:56 [Server] ERROR Error occurred while enabling Reinforcement v1.1 (Is it up to date?)
20.05 16:29:56 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.forEach(java.util.function.Consumer)" because the return value of "codes.zucker.reinforcement.util.ConfigurationYaml.getList(String)" is null
20.05 16:29:56 [Server] INFO at codes.zucker.reinforcement.ReinforcementPlugin.onEnable(ReinforcementPlugin.java:27) ~[Reinforcement.jar:?]

**Comment by trevor99z** [comment]
Try removing your config.yml and reloading the plugin.

**Comment by trevor99z** [comment]
This should be fixed in [1.1 hotfix](https://github.com/trevor99z/Reinforcement/releases/tag/1.19.4-hotfix)
